# Generated by Django 2.0 on 2018-10-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='danwei',
            field=models.CharField(default='指 挥 部', max_length=50),
        ),
    ]
