# Generated by Django 2.1.1 on 2018-09-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
