# Generated by Django 2.1.1 on 2018-09-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20180918_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='no',
            field=models.CharField(default='', max_length=32),
        ),
    ]
