# Generated by Django 2.1.1 on 2018-09-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userinfo_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
