# Generated by Django 2.0 on 2018-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20180922_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='yuanyi',
            new_name='yuanyin',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='bref',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='bendanweirenshu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nianlingduan',
            field=models.CharField(default='', max_length=20),
        ),
    ]
