# Generated by Django 2.0 on 2018-09-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20180922_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='danwei',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jianzhengren',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jianzhengrenzhiwu',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='keshi',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mubiao',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nianlingduan',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shouji',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shuiping',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='xiangmu',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='xuanyan',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='yuanyin',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zhaopian',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
