# Generated by Django 2.0 on 2018-09-22 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20180922_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='danwei',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jianzhengren',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='jianzhengrenzhiwu',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='keshi',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mubiao',
            field=models.CharField(default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='neirong',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nianlingduan',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='no',
            field=models.CharField(default='', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shouji',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='shuiping',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='xiangmu',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='xuanyan',
            field=models.CharField(default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='yuanyin',
            field=models.CharField(default=' ', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='zhaopian',
            field=models.CharField(default=' ', max_length=1000, null=True),
        ),
    ]
