# Generated by Django 2.0 on 2018-09-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicsInfo',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=256)),
                ('date', models.IntegerField()),
                ('no', models.CharField(max_length=32)),
            ],
        ),
    ]
