# Generated by Django 2.0 on 2018-09-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picsinfo',
            name='bref',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
