# Generated by Django 2.0 on 2018-10-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0002_picsinfo_bref'),
    ]

    operations = [
        migrations.AddField(
            model_name='picsinfo',
            name='comment',
            field=models.CharField(default='通过', max_length=218),
        ),
        migrations.AddField(
            model_name='picsinfo',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
