# Generated by Django 2.0 on 2018-10-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0003_auto_20181002_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picsinfo',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
