# Generated by Django 2.0 on 2018-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_auto_20181002_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='picsinfo',
            name='comment_author',
            field=models.IntegerField(default=1),
        ),
    ]
